### ISSUE TITLE
kivy[python] or java

### ISSUE THREAD

**Issue by juggernaut451** [GniotTechClub/Official-app#1]

**Comment by stalwart201** [comment]
Be specific with the question what kivy or java? @ashu94 give description

**Comment by juggernaut451** [comment]
The official application we would be creating can be created using two stack.
-> using native development language for android i.e JAVA 
-> using hybrid framework of python known as kivy which can result in android as well as ios app

**Comment by cosmologist10** [comment]
JAVA would be better.

**Comment by juggernaut451** [comment]
@rajatvaidya14 @stalwartrishabh @Shivams334 @Yourcyberfreak 
Suggestion please

**Comment by stalwart201** [comment]
go for java

**Comment by rajataaron** [comment]
choose according to the compatibility i think...

**Comment by juggernaut451** [comment]
we are using java

**Comment by ghost** [comment]
java
